export const taskScategory = [
  {
    "code":"first",
    "category":"01",
    "categoryName":"补填资料",
    "color":"label-blue",
    "detailPageUrl":"/system/resource-manage/edit/"
  },
  {
    "code":"second",
    "category":"02",
    "categoryName":"初审",
    "color":"label-blue",
    "detailPageUrl":""
  },
  {
    "code":"third",
    "category":"03",
    "categoryName":"复审",
    "color":"label-blue",
    "detailPageUrl":"",
  },
  {
    "code":"forth",
    "category":"04",
    "categoryName":"标的发布",
    "color":"label-blue",
    "detailPageUrl":""
  },
  {
    "code":"fifth",
    "category":"05",
    "categoryName":"流标",
    "color":"label-gold",
    "detailPageUrl":"label-pink"
  },
  {
    "sixth":"second",
    "category":"06",
    "categoryName":"满标审核",
    "color":"label-pink",
    "detailPageUrl":""
  },
  {
    "code":"seventh",
    "category":"07",
    "categoryName":"提前还款审核",
    "color":"label-green",
    "detailPageUrl":""
  }
];
