export const taskScategory = [
  {
    "code":"",
    "taskName": "全部",
    "detailPageUrl":"",
    "editPageUrl":""
  },
  {
    "code":"10",
    "taskName": "待补全资料",
    "detailPageUrl":"/business/intention/completion/",
    "editPageUrl":"/business/intention/detail/"
  },
  {
    "code":"20",
    "taskName":"待初审",
    "detailPageUrl":"",
    "editPageUrl":"/business/intention/firstAudit/"
  },
  {
    "code":"30",
    "taskName":"待复审",
    "detailPageUrl":"",
    "editPageUrl":""
  },
  {
    "code":"40",
    "taskName":"待标的发布",
    "detailPageUrl":"",
    "editPageUrl":""
  },
  {
    "code":"60",
    "taskName":"待满标审核",
    "detailPageUrl":"",
    "editPageUrl":""
  },
  {
    "code":"81",
    "taskName":"待提前还款审核",
    "detailPageUrl":"",
    "editPageUrl":""
  },
  {
    "code":"100",
    "taskName":"待提前还款审核",
    "detailPageUrl":"",
    "editPageUrl":""
  },

];
