export const taskScategory = [
  {
    "category":"01",
    "categoryName":"资料补全",
    "color":"label-blue",
    "detailPageUrl":"/system/resource-manage/edit/"
  },
  {
    "category":"02",
    "categoryName":"初审",
    "color":"label-blue",
    "detailPageUrl":""
  },
  {
    "category":"03",
    "categoryName":"复审",
    "color":"label-blue",
    "detailPageUrl":"",
  },
  {
    "category":"04",
    "categoryName":"标的发布",
    "color":"label-blue",
    "detailPageUrl":""
  },
  {
    "category":"05",
    "categoryName":"流标",
    "color":"label-gold",
    "detailPageUrl":"label-pink"
  },
  {
    "category":"06",
    "categoryName":"满标审核",
    "color":"label-pink",
    "detailPageUrl":""
  },
  {
    "category":"07",
    "categoryName":"提前还款审核",
    "color":"label-green",
    "detailPageUrl":""
  }
];
