export const TREE_EVENTS = {
  onToggle: 'onToggle',
  onToggleExpanded: 'onToggleExpanded',
  onActiveChanged: 'onActiveChanged',
  onActivate: 'onActivate',
  onDeactivate: 'onDeactivate',
  onFocus: 'onFocus',
  onBlur: 'onBlur',
  onDoubleClick: 'onDoubleClick',
  onContextMenu: 'onContextMenu',
  onInitialized: 'onInitialized',
  onUpdateData: 'onUpdateData',
  onLazyLoadChildren: 'onLazyLoadChildren',
  onEvent: 'onEvent',
  onAddNewNode: 'onAddNewNode',
  onRenameNode: 'onRenameNode',
  onDeleteNode: 'onDeleteNode',
  onMoveNode: 'onMoveNode',
  onClickNew: 'onClickNew',
  onClickEdit: 'onClickEdit',
};
